source 'https://rubygems.org'

# Modified gems (forked on github)
gem "handsoap", "~>0.2.5", :require => false, :git => "https://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-5"
gem "rubywbem",            :require => false, :git => "https://github.com/ManageIQ/rubywbem.git", :branch => "rubywbem_0_1_0"

group :appliance do
  gem "highline", "~> 1.6.21", :require => false  # Needed for the appliance_console
end

gem "winrm",                   "~>2.1",             :require => false
gem "winrm-elevated",          "~>1.0.1",           :require => false

# Linux-only section
if RbConfig::CONFIG["host_os"].include?("linux")
  gem "linux_block_device", ">=0.1.0", :require => false
end
